alias cat='bat --style=plain --paging=never --theme="Solarized (dark)"'
alias diff='diff --color=auto'
alias grep='grep --color=auto --exclude-dir={.git,.venv,venv}'
alias ls='ls --color=auto'
alias rm='trash-put --verbose'
alias xc='xsel --clipboard --input'
alias xp='xsel --clipboard --output'
