unbind-key -a -T prefix
unbind-key -a -T root

bind-key -T root M-0 select-window -t :=0
bind-key -T root M-1 select-window -t :=1
bind-key -T root M-2 select-window -t :=2
bind-key -T root M-3 select-window -t :=3
bind-key -T root M-4 select-window -t :=4
bind-key -T root M-5 select-window -t :=5
bind-key -T root M-6 select-window -t :=6
bind-key -T root M-7 select-window -t :=7
bind-key -T root M-8 select-window -t :=8
bind-key -T root M-9 select-window -t :=9

bind-key -T root M-: command-prompt

bind-key -T root M-c new-window

bind-key -T root M-h split-window -h
bind-key -T root M-v split-window -v

bind-key -T root M-w choose-tree -Zw

bind-key -T root M-Up select-pane -U
bind-key -T root M-Down select-pane -D
bind-key -T root M-Left select-pane -L
bind-key -T root M-Right select-pane -R
