[general]
import = [
"solarized_osaka.toml",
]

[window]
dimensions.columns = 120
dimensions.lines = 30
position = "None"
padding.x = 10
padding.y = 10
dynamic_padding = false
decorations = "Full"
opacity = 1.0
blur = false
startup_mode = "Windowed"
dynamic_title = true

[scrolling]
history = 100000
multiplier = 5

[font]
normal.family = "MesloLGMDZ Nerd Font Mono"
normal.style = "Regular"
size = 14.0

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
save_to_clipboard = false

[cursor]
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "Disabled"

[[hints.enabled]]
regex = ""
action = "Select"
