floating_modifier Mod4

# XF86AudioMute
bindcode --release 121 exec --no-startup-id C2 notify volume t
# XF86AudioLowerVolume
bindcode --release 122 exec --no-startup-id C2 notify volume d 10
# XF86AudioRaiseVolume
bindcode --release 123 exec --no-startup-id C2 notify volume i 10

# XF86MonBrightnessDown
bindcode 232 exec --no-startup-id C2 brightness - 20
# XF86MonBrightnessUp
bindcode 233 exec --no-startup-id C2 brightness + 20

# Mod4+Up
bindcode Mod4+111 focus up
# Mod4+Left
bindcode Mod4+113 focus left
# Mod4+Right
bindcode Mod4+114 focus right
# Mod4+Down
bindcode Mod4+116 focus down

# Mod4+Shift+Up
bindcode Mod4+Shift+111 move up
# Mod4+Shift+Left
bindcode Mod4+Shift+113 move left
# Mod4+Shift+Right
bindcode Mod4+Shift+114 move right
# Mod4+Shift+Down
bindcode Mod4+Shift+116 move down

# Mod4+f
bindcode Mod4+041 fullscreen toggle
# Mod4+h
bindcode Mod4+043 split horizontal
# Mod4+v
bindcode Mod4+055 split vertical

# Mod4+t
bindcode Mod4+028 layout tabbed
# Mod4+s
bindcode Mod4+039 layout stacking
# Mod4+n
bindcode Mod4+057 layout toggle split

# Mod4+p
bindcode Mod4+033 focus parent
# Mod4+c
bindcode Mod4+054 focus child

# Mod4+minus
bindcode Mod4+021 scratchpad show
# Mod4+Shift+minus
bindcode Mod4+Shift+021 move scratchpad

# Mod4+space
bindcode Mod4+065 focus mode_toggle
# Mod4+Shift+space
bindcode Mod4+Shift+065 floating toggle

# Mod4+Shift+q
bindcode --release Mod4+Shift+024 kill
# Mod4+Shift+Control+q
bindcode --release Mod4+Shift+Control+024 [floating] kill

# Mod4+Shift+r
bindcode --release Mod4+Shift+027 reload
# Mod4+Shift+Control+r
bindcode --release Mod4+Shift+Control+027 restart

# Mod4+1
bindcode Mod4+010 workspace number 1
# Mod4+2
bindcode Mod4+011 workspace number 2
# Mod4+3
bindcode Mod4+012 workspace number 3
# Mod4+4
bindcode Mod4+013 workspace number 4
# Mod4+5
bindcode Mod4+014 workspace number 5
# Mod4+6
bindcode Mod4+015 workspace number 6
# Mod4+7
bindcode Mod4+016 workspace number 7
# Mod4+8
bindcode Mod4+017 workspace number 8
# Mod4+9
bindcode Mod4+018 workspace number 9

# Mod4+Shift+1
bindcode Mod4+Shift+010 move container to workspace number 1
# Mod4+Shift+2
bindcode Mod4+Shift+011 move container to workspace number 2
# Mod4+Shift+3
bindcode Mod4+Shift+012 move container to workspace number 3
# Mod4+Shift+4
bindcode Mod4+Shift+013 move container to workspace number 4
# Mod4+Shift+5
bindcode Mod4+Shift+014 move container to workspace number 5
# Mod4+Shift+6
bindcode Mod4+Shift+015 move container to workspace number 6
# Mod4+Shift+7
bindcode Mod4+Shift+016 move container to workspace number 7
# Mod4+Shift+8
bindcode Mod4+Shift+017 move container to workspace number 8
# Mod4+Shift+9
bindcode Mod4+Shift+018 move container to workspace number 9

# Mod4+e
bindcode --release Mod4+026 exec --no-startup-id thunar

# Mod4+Return
bindcode --release Mod4+036 exec --no-startup-id alacritty

# Mod4+l
bindcode --release Mod4+046 exec --no-startup-id loginctl lock-session

# Mod4+Print
bindcode --release Mod4+107 exec --no-startup-id flameshot launcher

# Mod4+d
bindcode --release Mod4+040 exec --no-startup-id C2 menu drun

# Mod4+F4
bindcode --release Mod4+070 exec --no-startup-id C2 menu power

mode "*" {
    # Up
    bindcode 111 resize grow height 50 px
    # Left
    bindcode 113 resize shrink width 50 px
    # Right
    bindcode 114 resize grow width 50 px
    # Down
    bindcode 116 resize shrink height 50 px

    # Escape
    bindcode 009 mode default
    # Return
    bindcode 036 mode default

    # Mod4+r
    bindcode Mod4+027 mode default
}
    # Mod4+r
    bindcode Mod4+027 mode "*"
