floating_modifier Mod4

# XF86AudioMute
bindcode --release 121 exec --no-startup-id C2 notify volume t
# XF86AudioLowerVolume
bindcode --release 122 exec --no-startup-id C2 notify volume d 10
# XF86AudioRaiseVolume
bindcode --release 123 exec --no-startup-id C2 notify volume i 10

# XF86MonBrightnessDown
bindcode 232 exec --no-startup-id C2 brightness - 20
# XF86MonBrightnessUp
bindcode 233 exec --no-startup-id C2 brightness + 20

# Up
bindcode Mod4+111 focus up
# Left
bindcode Mod4+113 focus left
# Right
bindcode Mod4+114 focus right
# Down
bindcode Mod4+116 focus down

# Up
bindcode Mod4+Shift+111 move up
# Left
bindcode Mod4+Shift+113 move left
# Right
bindcode Mod4+Shift+114 move right
# Down
bindcode Mod4+Shift+116 move down

# f
bindcode Mod4+041 fullscreen toggle
# h
bindcode Mod4+043 split h
# v
bindcode Mod4+055 split v

# p
bindcode Mod4+033 focus parent
# c
bindcode Mod4+054 focus child

# minus
bindcode Mod4+021 scratchpad show
# minus
bindcode Mod4+Shift+021 move scratchpad

# space
bindcode Mod4+065 focus mode_toggle
# space
bindcode Mod4+Shift+065 floating toggle

# q
bindcode --release Mod4+Shift+024 kill
# q
bindcode --release Mod4+Shift+Control+024 [floating] kill

# r
bindcode --release Mod4+Shift+027 reload
# r
bindcode --release Mod4+Shift+Control+027 restart

# 1
bindcode Mod4+010 workspace number 1
# 2
bindcode Mod4+011 workspace number 2
# 3
bindcode Mod4+012 workspace number 3
# 4
bindcode Mod4+013 workspace number 4
# 5
bindcode Mod4+014 workspace number 5
# 6
bindcode Mod4+015 workspace number 6
# 7
bindcode Mod4+016 workspace number 7
# 8
bindcode Mod4+017 workspace number 8
# 9
bindcode Mod4+018 workspace number 9

# 1
bindcode Mod4+Shift+010 move container to workspace number 1
# 2
bindcode Mod4+Shift+011 move container to workspace number 2
# 3
bindcode Mod4+Shift+012 move container to workspace number 3
# 4
bindcode Mod4+Shift+013 move container to workspace number 4
# 5
bindcode Mod4+Shift+014 move container to workspace number 5
# 6
bindcode Mod4+Shift+015 move container to workspace number 6
# 7
bindcode Mod4+Shift+016 move container to workspace number 7
# 8
bindcode Mod4+Shift+017 move container to workspace number 8
# 9
bindcode Mod4+Shift+018 move container to workspace number 9

# e
bindcode --release Mod4+026 exec --no-startup-id thunar

# Return
bindcode --release Mod4+036 exec --no-startup-id alacritty

# l
bindcode --release Mod4+046 exec --no-startup-id loginctl lock-session

# Print
bindcode --release Mod4+107 exec --no-startup-id flameshot launcher

# d
bindcode --release Mod4+040 exec --no-startup-id C2 menu drun

# F4
bindcode --release Mod4+070 exec --no-startup-id C2 menu power

mode "*" {
    # Up
    bindcode 111 resize grow height 50 px
    # Left
    bindcode 113 resize shrink width 50 px
    # Right
    bindcode 114 resize grow width 50 px
    # Down
    bindcode 116 resize shrink height 50 px

    # Escape
    bindcode 009 mode default
    # Return
    bindcode 036 mode default

    # r
    bindcode Mod4+027 mode default
}
    # r
    bindcode Mod4+027 mode "*"
