floating_modifier Mod4

bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl set 20%-
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl set 20%+

bindsym XF86AudioPlay exec --no-startup-id playerctl --all-players play-pause
bindsym XF86AudioStop exec --no-startup-id playerctl --all-players stop
bindsym XF86AudioPrev exec --no-startup-id playerctl --all-players previous
bindsym XF86AudioNext exec --no-startup-id playerctl --all-players next

bindsym XF86AudioMute exec --no-startup-id C2 notify volume t
bindsym XF86AudioLowerVolume exec --no-startup-id C2 notify volume d 5
bindsym XF86AudioRaiseVolume exec --no-startup-id C2 notify volume i 5

bindsym Mod4+Left focus left
bindsym Mod4+Right focus right
bindsym Mod4+Up focus up
bindsym Mod4+Down focus down

bindsym Mod4+Tab focus next
bindsym Mod4+Shift+Tab focus prev

bindsym Mod4+Shift+Left move left
bindsym Mod4+Shift+Right move right
bindsym Mod4+Shift+Up move up
bindsym Mod4+Shift+Down move down

bindsym Mod4+h split h
bindsym Mod4+v split v
bindsym Mod4+f fullscreen toggle

bindsym Mod4+s layout stacking
bindsym Mod4+t layout tabbed
bindsym Mod4+n layout toggle split

bindsym Mod4+space focus mode_toggle
bindsym Mod4+Shift+space floating toggle
bindsym Mod4+Shift+Control+space sticky toggle

bindsym Mod4+minus scratchpad show
bindsym Mod4+Shift+minus move scratchpad

bindsym Mod4+p focus parent
bindsym Mod4+c focus child

set $1 1
set $2 2
set $3 3
set $4 4
set $5 5
set $6 6
set $7 7
set $8 8
set $9 9

bindsym Mod4+1 workspace number $1
bindsym Mod4+2 workspace number $2
bindsym Mod4+3 workspace number $3
bindsym Mod4+4 workspace number $4
bindsym Mod4+5 workspace number $5
bindsym Mod4+6 workspace number $6
bindsym Mod4+7 workspace number $7
bindsym Mod4+8 workspace number $8
bindsym Mod4+9 workspace number $9

bindsym Mod4+Shift+1 move container to workspace number $1
bindsym Mod4+Shift+2 move container to workspace number $2
bindsym Mod4+Shift+3 move container to workspace number $3
bindsym Mod4+Shift+4 move container to workspace number $4
bindsym Mod4+Shift+5 move container to workspace number $5
bindsym Mod4+Shift+6 move container to workspace number $6
bindsym Mod4+Shift+7 move container to workspace number $7
bindsym Mod4+Shift+8 move container to workspace number $8
bindsym Mod4+Shift+9 move container to workspace number $9

bindsym Mod4+Shift+r reload
bindsym Mod4+Shift+Control+r restart

bindsym --release Mod4+Shift+q kill

# Screen capture
bindsym Print exec --no-startup-id flameshot launcher

# Screenshot
bindsym Mod4+Print exec --no-startup-id scrot -q 100 -Z 1

# Calculator
bindsym Mod4+quotedbl exec --no-startup-id mate-calc

# File manager
bindsym Mod4+e exec --no-startup-id thunar

# Screen locker
bindsym --release Mod4+l exec --no-startup-id loginctl lock-session

# Terminal emulator
bindsym Mod4+Return exec --no-startup-id alacritty

# Web browser
bindsym Mod4+w exec --no-startup-id firefox

# Application launcher
bindcode --release Mod4+040 exec --no-startup-id C2 menu drun

# Power menu
bindcode --release Mod4+070 exec --no-startup-id C2 menu power

# Window switcher
bindcode --release Mod1+023 exec --no-startup-id C2 menu window

mode "*" {
    bindsym Left resize shrink width 50 px
    bindsym Right resize grow width 50 px
    bindsym Up resize grow height 50 px
    bindsym Down resize shrink height 50 px

    bindsym Return mode default
    bindsym Escape mode default

    bindsym Mod4+r mode default
}
    bindsym Mod4+r mode "*"
