floating_modifier Mod4

bindcode 232 exec --no-startup-id brightnessctl set 20%-
bindcode 233 exec --no-startup-id brightnessctl set 20%+

bindcode 172 exec --no-startup-id playerctl --all-players play-pause
bindcode 174 exec --no-startup-id playerctl --all-players stop
bindcode 173 exec --no-startup-id playerctl --all-players previous
bindcode 171 exec --no-startup-id playerctl --all-players next

bindcode 121 exec --no-startup-id C2 notify volume t
bindcode 122 exec --no-startup-id C2 notify volume d 5
bindcode 123 exec --no-startup-id C2 notify volume i 5

bindcode Mod4+113 focus left
bindcode Mod4+114 focus right
bindcode Mod4+111 focus up
bindcode Mod4+116 focus down

bindcode Mod4+Shift+113 move left
bindcode Mod4+Shift+114 move right
bindcode Mod4+Shift+111 move up
bindcode Mod4+Shift+116 move down

bindcode Mod4+043 split h
bindcode Mod4+055 split v

bindcode Mod4+041 fullscreen toggle
bindcode Mod4+057 layout toggle split

bindcode Mod4+054 focus child
bindcode Mod4+028 focus parent

bindcode Mod4+023 focus next
bindcode Mod4+Shift+023 focus prev

bindcode Mod4+021 scratchpad show
bindcode Mod4+Shift+021 move scratchpad

bindcode Mod4+065 focus mode_toggle
bindcode Mod4+Shift+065 floating toggle

set $1 "1:I"
set $2 "2:II"
set $3 "3:III"
set $4 "4:IV"
set $5 "5:V"
set $6 "6:VI"
set $7 "7:VII"
set $8 "8:VIII"
set $9 "9:IX"

bindcode Mod4+010 workspace number $1
bindcode Mod4+011 workspace number $2
bindcode Mod4+012 workspace number $3
bindcode Mod4+013 workspace number $4
bindcode Mod4+014 workspace number $5
bindcode Mod4+015 workspace number $6
bindcode Mod4+016 workspace number $7
bindcode Mod4+017 workspace number $8
bindcode Mod4+018 workspace number $9

bindcode Mod4+Shift+010 move container to workspace number $1
bindcode Mod4+Shift+011 move container to workspace number $2
bindcode Mod4+Shift+012 move container to workspace number $3
bindcode Mod4+Shift+013 move container to workspace number $4
bindcode Mod4+Shift+014 move container to workspace number $5
bindcode Mod4+Shift+015 move container to workspace number $6
bindcode Mod4+Shift+016 move container to workspace number $7
bindcode Mod4+Shift+017 move container to workspace number $8
bindcode Mod4+Shift+018 move container to workspace number $9

bindcode --release Mod4+024 reload
bindcode --release Mod4+Shift+024 kill
bindcode --release Mod4+Shift+Control+024 restart

# Screen locker
bindcode --release Mod4+046 exec --no-startup-id loginctl lock-session

# File manager
bindcode --release Mod4+026 exec --no-startup-id thunar

# Terminal emulator
bindcode --release Mod4+036 exec --no-startup-id alacritty

# Screen capture
bindcode --release 107 exec --no-startup-id flameshot launcher

# Application launcher
bindcode --release Mod4+040 exec --no-startup-id C2 menu drun

# Power menu
bindcode --release Mod4+033 exec --no-startup-id C2 menu power

mode "*" {
    bindcode 113 resize shrink width 50 px
    bindcode 114 resize grow width 50 px
    bindcode 111 resize grow height 50 px
    bindcode 116 resize shrink height 50 px

    bindcode 036 mode default
    bindcode 009 mode default

    bindcode Mod4+027 mode default
}
    bindcode Mod4+027 mode "*"
