bar {
    status_command i3status

    mode dock
    hidden_state hide
    modifier none

    bindsym button2 nop
    bindsym button3 nop
    bindsym button4 nop
    bindsym button5 nop
    bindsym button6 nop
    bindsym button7 nop

    id bar-1

    position top

    tray_output primary

    tray_padding 0

    separator_symbol " "

    workspace_buttons yes

    workspace_min_width 50

    strip_workspace_numbers no
    strip_workspace_name no

    binding_mode_indicator yes

    colors {
        background              "#000000"
        statusline              "#888888"
        separator               "#000000"

        focused_workspace       "#1f1f1f" "#1f1f1f" "#ffffff"
        active_workspace        "#000000" "#000000" "#ffffff"
        inactive_workspace      "#000000" "#000000" "#ffffff"
        urgent_workspace        "#ff0000" "#ff0000" "#000000"
        binding_mode            "#cc7722" "#cc7722" "#000000"
    }

    padding 20 0 20 0
}
