font pango:Noto Sans Mono 14

title_align left

default_border normal 5
default_floating_border normal 5

hide_edge_borders both

for_window [all] title_format "%instance:%class"

for_window [floating] border normal 5 move position center

client.focused              "#116062" "#116062" "#000000" "#116062" "#116062"
client.focused_inactive     "#1f1f1f" "#1f1f1f" "#000000" "#1f1f1f" "#1f1f1f"
client.unfocused            "#1f1f1f" "#1f1f1f" "#000000" "#1f1f1f" "#1f1f1f"
client.urgent               "#ff0000" "#ff0000" "#000000" "#ff0000" "#ff0000"
client.placeholder          "#000000" "#000000" "#000000" "#000000" "#000000"
client.background           "#000000"
