font pango:Noto Sans Mono 14

title_align left

default_border normal 5
default_floating_border normal 5

hide_edge_borders both

for_window [all] title_format "%title"

for_window [floating] border normal 5 move position center

# <colorclass>              <border>     <background> <text>       <indicator>  <child_border>
client.focused              "#116062"    "#116062"    "#000000"    "#116062"    "#116062"
client.focused_inactive     "#301934"    "#301934"    "#000000"    "#301934"    "#301934"
client.focused_tab_title    "#116062"    "#116062"    "#000000"
client.unfocused            "#1f1f1f"    "#1f1f1f"    "#000000"    "#1f1f1f"    "#1f1f1f"
client.urgent               "#880808"    "#880808"    "#000000"    "#880808"    "#880808"
client.placeholder          "#000000"    "#000000"    "#000000"    "#000000"    "#000000"
client.background           "#000000"
