[general]
import = [
"solarized_osaka.toml",
]

[window]
dimensions.columns = 120
dimensions.lines = 30
position = "None"
padding.x = 0
padding.y = 0
dynamic_padding = false
decorations = "Full"
opacity = 1.0
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"

[scrolling]
history = 100000
multiplier = 10

[font]
normal.family = "MesloLGMDZ Nerd Font Mono"
normal.style = "Regular"
bold.style = "Regular"
italic.style = "Italic"
bold_italic.style = "Italic"
size = 14.0
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
save_to_clipboard = false

[cursor]
style.shape = "Block"
style.blinking = "Never"
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "Disabled"

[[hints.enabled]]
regex = ""
action = "Select"
