[general]
import=[
"colors.toml",
"themes/solarized_osaka.toml",
]

[window.padding]
x=5
y=5

[scrolling]
history=100000

[font.normal]
family="MesloLGMDZ Nerd Font Mono"

[font.bold]
style="Regular"

[font.italic]
style="Italic"

[font.bold_italic]
style="Italic"

[font]
size=14.0

[font.offset]
x=0
y=0

[bell]
duration=0

[selection]
save_to_clipboard=false

[cursor.style]
shape="Block"

[cursor]
unfocused_hollow=true

[terminal]
osc52="Disabled"

[mouse]
hide_when_typing=true

[[hints.enabled]]
command="xdg-open"
regex=""
