[general]
import = [
"colors.toml",
"alacritty-theme/themes/solarized_osaka.toml",
]

[window.padding]
x = 5
y = 5

[window]
dynamic_padding = false
decorations = "Full"
opacity = 1.0
dynamic_title = true

[scrolling]
history = 100000
multiplier = 5

[font.normal]
family = "MesloLGMDZ Nerd Font Mono"
style = "Regular"

[font.bold]
style = "Regular"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Italic"

[font]
size = 14.0

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[bell]
duration = 0

[selection]
save_to_clipboard = false

[cursor.style]
shape = "Block"
blinking = "Never"

[cursor]
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "Disabled"

[mouse]
hide_when_typing = true

[[hints.enabled]]
regex = ""
action = "Select"
